awesome_nornik_stocks/urls.py
from django.urls import path, include
from .views import StockList


urlpatterns = [
    path('', StockList.as_view(), name='stocks'),
]

nornik_test_case/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('awesome_nornik_stocks.urls')),
]

awesome_nornik_stocks/models.py
from django.db import models
import django


# Timeline for stocks
class Timefeed(models.Model):
    timestamp = models.DateTimeField(('Дата'), default=django.utils.timezone.now)

    class Meta:
        verbose_name_plural = 'Stock timeline'

    def __str__(self):
        return self.timestamp.strftime("%d.%m.%Y %H:%M")


# Main stocks model with attrs
class Stock(models.Model):

    stock_name = models.CharField(('Компания'), max_length=64)
    stock_price = models.DecimalField(('Цена акции'), max_digits=9, decimal_places=2)
    timestamp = models.ForeignKey(Timefeed, related_name='stock_time', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Stocks'

    def __str__(self):
        return str('Компания: {}, Акция: {}'.format(self.stock_name, self.stock_price))

awesome_nornik_stocks/views.py
from .models import Stock, Timefeed
from django.shortcuts import render
from datetime import datetime, date, time, timedelta
from django.utils import timezone
from django.views.generic import ListView


# Stocks view list for rendering 3 components: table, pagination, template
class StockList(ListView):

    model = Stock
    paginate_by = 60
    context_object_name = 'stocks'

    def get_queryset(self):
        return Stock.objects.all().order_by("-timestamp", "stock_name")

    def get_template_names(self):
        if self.request.is_ajax():
            if self.request.GET.get('pagination'):
                return ['pagination.html']
            else:
                return ['table.html']
        return ['stock.html']

awesome_nornik_stocks/templates/pagination.html
{% if is_paginated %}
<div id="exist" class="pagination">
  <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group mr-2" role="group" aria-label="First group">
      {% if page_obj.has_previous %}
      <button type="button" class="btn btn-dark" href="?page=1">first</button>
      <button type="button" class="btn btn-dark" aria-label="Previous" href="?page={{ page_obj.previous_page_number }}">«</button>
      {% endif %}
      <button type="button" class="btn btn-dark disabled">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </button>
      {% if page_obj.has_next %}
      <button type="button" class="btn btn-dark" aria-label="Next" href="?page={{ page_obj.next_page_number }}">»</button>
      <button type="button" class="btn btn-dark" href="?page={{ page_obj.paginator.num_pages }}">last</button>
      {% endif %}
    </div>
  </div>
</div>
{% endif %}

awesome_nornik_stocks/templates/stock.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <div class="row justify-content-center">
    <h1>Welcome to Awesome Nickel Stocks</h1>
  </div>

  <div class="container-fluid">
    <div id="stocks" class="p-1 m-1">
      <div class="row justify-content-center">
        <div class="alert alert-dark">
          <h2>Загрузка данных....</h2>

        </div>
      </div>
    </div>
    <div id="pagination" class="p-1 m-1">
      {% include 'pagination.html' %}
    </div>

  </div>



  <script src="{% static 'awesome_nornik_stocks\js\nornik.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

awesome_nornik_stocks/templates/table.html
{% regroup stocks by timestamp as stock_list %}
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Datetime</th>
      <th scope="col">Apple</th>
      <th scope="col">Amazon</th>
      <th scope="col">Facebook</th>
      <th scope="col">Google</th>
      <th scope="col">Netflix</th>
      <th scope="col">Tesla</th>
    </tr>
  </thead>
  <tbody>
    {% for stock in stock_list %}

    <tr>
      <th scope="row">

        {{ stock.grouper }}

      </th>
      {% for stock_instance in stock.list%}
      <td>

        {{ stock_instance.stock_price }}

      </td>
      {% endfor %}
    </tr>
    {% endfor %}
  </tbody>
</table>